### ISSUE TITLE
How to upload a file to a Matlab production server (via CLI)

### ISSUE THREAD

**Issue by amchew** [mathworks-ref-arch/matlab-azure-cli#1]
Hi @asollander, 

We're looking to write a wrapper for our Matlab function that users will interface with via our CLI. This repo is helpful, thanks for sharing this. Our function takes in a file as a parameter, and users will have to upload a file using the CLI to the Matlab production server. We then pass the uploaded file as a parameter in our function. Would you mind sharing more details on how that will work?

**Comment by asollander** [comment]
Hi @amchew,

it's not quite clear to me what you're trying to do.

Are you uploading a data file to Azure storage, and then calling a function on your MATLAB Production Server (is this also on Azure) with the name of that file/blob, to make it process it? Or are you uploading a `.ctf` to the `auto_deploy` folder of MATLAB Production Server?

**Comment by amchew** [comment]
Hi @asollander, we have a local Matlab production server (that hasn't been deployed to the cloud). Can the Matlab production server handle file uploads directly (via the CLI) without these files being uploaded to the cloud?

**Comment by asollander** [comment]
Hi @amchew, 
if you can do it in MATLAB (with the Azure CLI), you can do it with MATLAB Production Server too. If you use the az.* functions in MATLAB Production Server, it should work just as in MATLAB. You must make sure that the Azure CLI (command line) is also installed on the machine where MATLAB Production Server is running, and that you have proper credentials in place.

**Comment by amchew** [comment]
Thanks for the helpful reply.
